// Code generated by ent, DO NOT EDIT.

package city

const (
	// Label holds the string label denoting the city type in the database.
	Label = "city"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldCountryCode holds the string denoting the countrycode field in the database.
	FieldCountryCode = "country_code"
	// FieldDistrict holds the string denoting the district field in the database.
	FieldDistrict = "district"
	// FieldPopulation holds the string denoting the population field in the database.
	FieldPopulation = "population"
	// Table holds the table name of the city in the database.
	Table = "cities"
)

// Columns holds all SQL columns for city fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldCountryCode,
	FieldDistrict,
	FieldPopulation,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// NameValidator is a validator for the "Name" field. It is called by the builders before save.
	NameValidator func(string) error
	// CountryCodeValidator is a validator for the "CountryCode" field. It is called by the builders before save.
	CountryCodeValidator func(string) error
	// DistrictValidator is a validator for the "District" field. It is called by the builders before save.
	DistrictValidator func(string) error
)
